Repository eclipse-che/che-theia, pull requests merged in 2019-09, with the labels that each got.

#420 Fix building clang docker image
  dockerfiles/remote-plugin-clang-8/Dockerfile
Labels: kind/bug

#413 Add devfile and doc for developing of Che Theia remote plugin mechanism
  CONTRIBUTING.md
  extensions/eclipse-che-theia-plugin-remote/devfile.yaml
Labels: kind/docs

#433 Change a command to populate local package cache for dotnet image
  dockerfiles/remote-plugin-dotnet-2.2.105/Dockerfile
Labels: status/code-review, team/languages

#429 Generate settings.xml if MAVEN_MIRROR_URL is set
  dockerfiles/remote-plugin-java11/Dockerfile
  dockerfiles/remote-plugin-java11/etc/before-start.sh
  dockerfiles/remote-plugin-java8/Dockerfile
  dockerfiles/remote-plugin-java8/etc/before-start.sh
  dockerfiles/theia-endpoint-runtime/etc/entrypoint.sh
Labels: kind/enhancement

#427 Use python:3.7.4-slim as a base image for python
  dockerfiles/remote-plugin-python-3.7.3/Dockerfile
Labels: kind/enhancement

#424 Add ability to set up git user name and email in theia preferences
  che-theia-init-sources.yml
  extensions/eclipse-che-theia-git-provisioner/.gitignore
  extensions/eclipse-che-theia-git-provisioner/package.json
  extensions/eclipse-che-theia-git-provisioner/src/browser/git-frontend-module.ts
  extensions/eclipse-che-theia-git-provisioner/src/browser/git-preferences.ts
  extensions/eclipse-che-theia-git-provisioner/src/node/git-backend-module.ts
  extensions/eclipse-che-theia-git-provisioner/src/node/git-configuration-contribution.ts
  extensions/eclipse-che-theia-git-provisioner/src/node/git-configuration-controller.ts
  extensions/eclipse-che-theia-git-provisioner/tsconfig.json
  extensions/eclipse-che-theia-user-preferences/src/node/che-theia-preferences-synchronizer.ts
  extensions/eclipse-che-theia-user-preferences/tsconfig.json
Labels: kind/enhancement, status/code-review
