Repository eclipse-che/che-theia, pull requests merged in 2019-10, with the labels that each got.

#443 Update go version to 1.12.9
  docker_image_build.include
  dockerfiles/remote-plugin-go-1.12.9/.gitignore
  dockerfiles/remote-plugin-go-1.12.9/Dockerfile
  dockerfiles/remote-plugin-go-1.12.9/build.sh
Labels: kind/task

#480 Add _scope to TaskConfiguration
  extensions/eclipse-che-theia-plugin/src/che-proposed.d.ts
  plugins/task-plugin/src/task/converter.ts
  yarn.lock
Labels: kind/bug

#495 Resolve preview URL for notification
  plugins/task-plugin/src/preview/task-events-handler.ts
Labels: kind/bug

#511 Fix message of sparse checkout to fit template
  plugins/factory-plugin/src/theia-commands.ts
Labels: kind/enhancement
