Repository eclipse-che/che-theia, pull requests merged in 2019-07, with the labels that each got.

#338 Removing unused che-theia plugin tar.gz build
  che-plugins/build.sh
  che-plugins/che-editor-theia/.gitignore
  che-plugins/che-editor-theia/README.md
  che-plugins/che-editor-theia/build.sh
  che-plugins/che-editor-theia/etc/che-plugin.yaml
Labels: team/ide2

#326 README: Adding contribution section based on devfile + provide devfile
  CONTRIBUTING.md
  README.md
  devfiles/che-theia-all.devfile.yaml
Labels: kind/docs

#348 Fix /go/pkg folder permissions
  dockerfiles/remote-plugin-go-1.10.7/Dockerfile
Labels: kind/enhancement

#351 Fix /go/pkg folder permissions (#348)
  dockerfiles/remote-plugin-go-1.10.7/Dockerfile
Labels: kind/enhancement

#364 Fix permissions on $GOPATH folder
  dockerfiles/remote-plugin-go-1.10.7/Dockerfile
Labels: kind/enhancement

#363 Fix permissions on $GOPATH folder
  dockerfiles/remote-plugin-go-1.10.7/Dockerfile
Labels: kind/enhancement
