Repository eclipse-che/che-theia, pull requests merged in 2019-04, with the labels that each got.

#158 Replace python 3.7.2 on 3.7.3
  build_and_push_docker_images.sh
  dockerfiles/remote-plugin-python-3.7.3/Dockerfile
  dockerfiles/remote-plugin-python-3.7.3/build.sh
Labels: kind/enhancement, team/languages

#181 Introduce Che Theia about menu instead of Theia one
  extensions/eclipse-che-theia-about/.gitignore
  extensions/eclipse-che-theia-about/package.json
  extensions/eclipse-che-theia-about/scripts/generate-about-details.js
  extensions/eclipse-che-theia-about/src/browser/about-che-theia-dialog.ts
  extensions/eclipse-che-theia-about/src/browser/about-frontend-module.ts
  extensions/eclipse-che-theia-about/src/browser/style/che-logo-dark.svg
  extensions/eclipse-che-theia-about/src/browser/style/che-logo-light.svg
  extensions/eclipse-che-theia-about/tsconfig.json
  extensions/extensions.yml
Labels: kind/enhancement

#183 Do not override task plugin handlers
  extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-client.ts
Labels: kind/bug
