Repository eclipse-che/che-theia, pull requests merged in 2020-07, with the labels that each got.

#788 Freeze version of workspace-client library
  extensions/che-theia-hosted-plugin-manager-extension/package.json
  extensions/eclipse-che-theia-plugin-ext/package.json
  extensions/eclipse-che-theia-terminal/package.json
  yarn.lock
Labels: kind/task

#790 Keep machine exec connection
  extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
  plugins/task-plugin/src/machine/machine-exec-client.ts
  plugins/task-plugin/src/machine/websocket.ts
Labels: kind/bug

#789 Provide ability to call filtered workspace service methods using user token
  dockerfiles/theia/e2e/test.sh
  extensions/che-theia-hosted-plugin-manager-extension/package.json
  extensions/che-theia-hosted-plugin-manager-extension/src/node/che-workspace-hosted-plugin-uri-post-processor.ts
  extensions/eclipse-che-theia-plugin-ext/package.json
  extensions/eclipse-che-theia-plugin-ext/src/browser/che-devfile-main.ts
  extensions/eclipse-che-theia-plugin-ext/src/browser/che-task-resolver.ts
  extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
  extensions/eclipse-che-theia-plugin-ext/src/node/che-api-service.ts
  extensions/eclipse-che-theia-terminal/package.json
  extensions/eclipse-che-theia-terminal/src/node/workspace-service-impl.ts
  yarn.lock
Labels: kind/bug

#800 Show recent Che workspaces in Theia editor
  che-theia-init-sources.yml
  dockerfiles/theia/e2e/cypress/integration/theia/typescript.spec.ts
  extensions/eclipse-che-theia-workspace/.gitignore
  extensions/eclipse-che-theia-workspace/package.json
  extensions/eclipse-che-theia-workspace/src/browser/che-quick-open-workspace.ts
  extensions/eclipse-che-theia-workspace/src/browser/che-workspace-contribution.ts
  extensions/eclipse-che-theia-workspace/src/browser/che-workspace-module.ts
  extensions/eclipse-che-theia-workspace/tsconfig.json
Labels: kind/enhancement
