Repository eclipse-che/che-theia, pull requests merged in 2020-03, with the labels that each got.

#652 Adaptate terminal to the upstream
  extensions/eclipse-che-theia-terminal/package.json
  extensions/eclipse-che-theia-terminal/src/browser/terminal-frontend-module.ts
  extensions/eclipse-che-theia-terminal/src/browser/terminal-widget/remote-terminal-widget.ts
  generator/tests/init-sources/assembly-example/configs/root-compilation.tsconfig.json
  yarn.lock
Labels: kind/task

#651 Provide timestamp in console logs
  che-theia-init-sources.yml
  extensions/eclipse-che-theia-logging/.gitignore
  extensions/eclipse-che-theia-logging/package.json
  extensions/eclipse-che-theia-logging/src/node/formatted-console-logger-backend-module.ts
  extensions/eclipse-che-theia-logging/src/node/formatted-console-logger-server.ts
  extensions/eclipse-che-theia-logging/tsconfig.json
  generator/src/templates/assembly-compile.tsconfig.json
  yarn.lock
Labels: kind/enhancement

#675 Upgrade yarn to 1.21.1
  CONTRIBUTING.md
  README.md
  devfiles/che-theia-all.devfile.yaml
  devfiles/hosted-che-dogfooding.devfile.yaml
  dockerfiles/theia-dev/docker/alpine/builder-image-from.dockerfile
  dockerfiles/theia-dev/docker/ubi8/setup-yarn.dockerfile
  dockerfiles/theia/Dockerfile
  dockerfiles/theia/README.md
  dockerfiles/theia/docker/alpine/runtime-from.dockerfile
  dockerfiles/theia/docker/alpine/runtime-setup-yarn.dockerfile
  dockerfiles/theia/docker/ubi8/runtime-setup-yarn.dockerfile
  extensions/eclipse-che-theia-plugin-remote/devfile.yaml
  generator/README.md
  generator/package.json
Labels: kind/task, severity/P2

#690 Support proxy in plugin service
  extensions/eclipse-che-theia-plugin-ext/package.json
  extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
  yarn.lock
Labels: kind/bug

#692 Support proxy configuration in plugin service
  extensions/eclipse-che-theia-plugin-ext/package.json
  extensions/eclipse-che-theia-plugin-ext/src/node/che-plugin-service.ts
  yarn.lock
Labels: kind/bug
