Repository eclipse-che/che-theia, pull requests merged in 2020-12, with the labels that each got.

#943 Make Che-Theia spelling consistent with the docs
  CONTRIBUTING.md
  README.md
  RELEASE.md
  dockerfiles/theia-dev/Dockerfile
  dockerfiles/theia-dev/build.sh
  dockerfiles/theia/README.md
  dockerfiles/theia/src/entrypoint.sh
  extensions/eclipse-che-theia-about/scripts/generate-about-details.js
  extensions/eclipse-che-theia-dashboard/src/browser/theia-dashboard-client.ts
  extensions/eclipse-che-theia-plugin-remote/devfile.yaml
  extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-backend-module.ts
  generator/README.md
  make-release.sh
  plugins/workspace-plugin/README.md
Labels: kind/enhancement

#952 Use express library instead redundant connect
  extensions/eclipse-che-theia-plugin-ext/src/node/plugin-service.ts
Labels: kind/task, severity/blocker

#946 Implement simple side car file system which fetches file content
  extensions/eclipse-che-theia-plugin-ext/package.json
  extensions/eclipse-che-theia-plugin-ext/src/browser/che-api-provider.ts
  extensions/eclipse-che-theia-plugin-ext/src/browser/che-sidecar-file-system-main.ts
  extensions/eclipse-che-theia-plugin-ext/src/common/che-protocol.ts
  extensions/eclipse-che-theia-plugin-ext/src/plugin/che-api.ts
  extensions/eclipse-che-theia-plugin-ext/src/plugin/che-sidecar-file-system.ts
  yarn.lock
Labels: kind/task, severity/P1

#947 Support webview in dedicate container
  extensions/eclipse-che-theia-plugin-remote/src/node/plugin-remote-init.ts
  extensions/eclipse-che-theia-plugin-remote/src/node/webviews-content-aware.ts
Labels: kind/bug, severity/P1
